### ISSUE TITLE
XMLLocalDateAdapter.unmarshal accepts 2006.01.01z

### ISSUE THREAD

**Issue by hestad** [ultraq/jaxb-utilities#9]
XMLLocalDateAdapter.unmarshal accepts 2006.01.01z, but this is not valid xsd:date format, it should only accept upper-case.

What do you think?

**Comment by ultraq** [comment]
Since the dates are all Joda Time implementations,I tend to accept what Joda Time does for these conversions so as not to surprise people using this library too much.  I can see that the `ISODateTimeFormat` is a little lenient in this regard:

> (from http://www.joda.org/joda-time/apidocs/org/joda/time/format/ISODateTimeFormat.html)
> 
> Note that these formatters mostly follow the ISO8601 standard for printing. For parsing, the formatters are more lenient and allow formats that are not in strict compliance with the standard.

So it's kinda a proponent of the [Robustness Principle](http://en.wikipedia.org/wiki/Robustness_principle), which I'm totally cool with.

If you do see it outputting non-ISO8601 dates though, then we have a problem :)
